//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Setting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelperNotifyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelperNotifyMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib.Setting.HelperNotifyMessage", typeof(HelperNotifyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is invalid at column {0} at row {1}.
        /// </summary>
        internal static string VALIDATE_EXCEL_INVALID_DATA {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format is not valid..
        /// </summary>
        internal static string VALIDATE_EXCEL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] column(s) is missing..
        /// </summary>
        internal static string VALIDATE_EXCEL_MISSING_COLUMNS {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_MISSING_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] column(s) is redundant..
        /// </summary>
        internal static string VALIDATE_EXCEL_REDUNDANT_COLUMNS {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_REDUNDANT_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is required at column {0} at row {1}.
        /// </summary>
        internal static string VALIDATE_EXCEL_REQUIRED_DATA {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_REQUIRED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is required at column [{0}].
        /// </summary>
        internal static string VALIDATE_EXCEL_REQUIRED_DATA_MES {
            get {
                return ResourceManager.GetString("VALIDATE_EXCEL_REQUIRED_DATA_MES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] contains invalid data..
        /// </summary>
        internal static string WARNING_CONTAINS_INVALID_DATA {
            get {
                return ResourceManager.GetString("WARNING_CONTAINS_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name [{0}] is invalid..
        /// </summary>
        internal static string WARNING_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("WARNING_DOES_NOT_EXIST", resourceCulture);
            }
        }
    }
}
